### ISSUE TITLE
Fails to build on ruby 3.3 with clang-1500.3.9.4

### ISSUE THREAD

**Issue by joeljunstrom** [ruby/iconv#25]
Given the last command line tools update on MacOS with a M1 iconv no longer builds.

Excerpt from the log:

```
iconv.c:709:50: error: incompatible function pointer types passing 'VALUE (VALUE, VALUE)' (aka 'unsigned long (unsigned long, unsigned long)') to parameter of type
'rb_block_call_func_t' (aka 'unsigned long (*)(unsigned long, unsigned long, int, const unsigned long *, unsigned long)') [-Wincompatible-function-pointer-types]
        rb_block_call(options, rb_intern("each"), 0, 0, get_iconv_opt_i, (VALUE)opt);
```

It does compile with `gem install iconv -- --with-cflags="-Wno-incompatible-function-pointer-types"`

**Comment by fabiode** [comment]
I can confirm it happened with an intel mac using `clang-1500.3.9.4`, could install using

`gem install iconv -- --with-cflags="-Wno-incompatible-function-pointer-types"` as @joeljunstrom mentioned. Thanks!

```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by ameeraazli** [comment]
> I can confirm it happened with an intel mac using `clang-1500.3.9.4`, could install using
> 
> `gem install iconv -- --with-cflags="-Wno-incompatible-function-pointer-types"` as @joeljunstrom mentioned. Thanks!
> 
> ```
> Apple clang version 15.0.0 (clang-1500.3.9.4)
> Target: x86_64-apple-darwin23.5.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> ```

encountered the same problem on my mac M2 chip, and this solution works! thanks!
