### PR TITLE
Use compatible function pointer types to fix build errors on newer Clang

### LINKED ISSUE #25: Fails to build on ruby 3.3 with clang-1500.3.9.4
Given the last command line tools update on MacOS with a M1 iconv no longer builds.

Excerpt from the log:

```
iconv.c:709:50: error: incompatible function pointer types passing 'VALUE (VALUE, VALUE)' (aka 'unsigned long (unsigned long, unsigned long)') to parameter of type
'rb_block_call_func_t' (aka 'unsigned long (*)(unsigned long, unsigned long, int, const unsigned long *, unsigned long)') [-Wincompatible-function-pointer-types]
        rb_block_call(options, rb_intern("each"), 0, 0, get_iconv_opt_i, (VALUE)opt);
```

It does compile with `gem install iconv -- --with-cflags="-Wno-incompatible-function-pointer-types"`

### PR DESCRIPTION
**Pull request by jeremy**
Fixes #25

### CODE REVIEW

**Comment by hsbt** [comment]
Thanks!

**Comment by noma4i** [comment]
Will it be released to rubygems?

**Comment by Adrian-Hirt** [comment]
@hsbt Any updates on this? Please let me know if I can be of any assistance.
